// API Phénix Perso simulée pour les tests d'interface : une situation type et un rapport par module.
"use strict";
const ETAT = {
  periode: { debut: "2026-06", fin: "2026-08", nb_mois: 3 }, source: "releve_bancaire", confiance: "haute", situation_devinee: "Salarié(e) vivant seul(e), locataire",
  revenus_mensuels: 2180, revenus_detail: [{ source: "Salaire ACME", montant_mensuel: 2180 }],
  depenses: [{ categorie: "logement", montant_mensuel: 780 }, { categorie: "energie_telecom", montant_mensuel: 95 }, { categorie: "alimentation", montant_mensuel: 340 }, { categorie: "transport", montant_mensuel: 120 }, { categorie: "assurances", montant_mensuel: 60 }, { categorie: "abonnements_loisirs", montant_mensuel: 84 }, { categorie: "restaurants_sorties", montant_mensuel: 210 }, { categorie: "frais_bancaires", montant_mensuel: 18 }, { categorie: "credits", montant_mensuel: 212 }, { categorie: "autres", montant_mensuel: 90 }],
  epargne_mensuelle: 50, epargne_disponible: 1400, solde_fin_periode: -120, decouvert_autorise: 400,
  mois: [{ mois: "2026-06", entrees: 2180, sorties: 2090, solde_fin: 210 }, { mois: "2026-07", entrees: 2180, sorties: 2310, solde_fin: 80 }, { mois: "2026-08", entrees: 2180, sorties: 2380, solde_fin: -120 }],
  dettes: [{ nom: "Crédit conso Sofinco", type: "credit_conso", capital_restant: 4200, taux: 6.9, mensualite: 212, echeance: "2028-06" }],
  recurrents: [{ libelle: "PRLV NETFLIX", montant_mensuel: 13.49, categorie: "streaming", occurrences: 3 }, { libelle: "PRLV SPOTIFY", montant_mensuel: 10.99, categorie: "streaming", occurrences: 3 }, { libelle: "PRLV BASIC FIT", montant_mensuel: 29.99, categorie: "sport", occurrences: 3 }, { libelle: "PRLV ORANGE", montant_mensuel: 19.99, categorie: "telecom", occurrences: 3 }],
  lignes_notables: [], alertes: ["Découvert en août : solde à −120 €", "Frais bancaires réguliers (agios)"], manquant: ["Montant de la taxe d'habitation"]
};
function rapport(mod) {
  const base = { titre: "", resume: "Tu gagnes 2 180 € et tu en dépenses 2 010 : ça passe, mais sans marge, et août a fini dans le rouge. Le plan libère 150 € par mois dès S4.", score: { global: 0, budget: 0, epargne: 0, depenses: 0, dettes: 0, securite: 0 }, kpis: [{ label: "Reste chaque mois", valeur: "170 €", detail: "avant épargne" }, { label: "Taux d'épargne", valeur: "2,3 %", detail: "50 € / mois" }, { label: "Épargne de sécurité", valeur: "0,7 mois", detail: "cible : 3 mois" }], diagnostic: [{ titre: "Sorties et livraisons : 210 € par mois", detail: "C'est ton premier poste variable. Pas de morale, mais c'est là qu'est la marge.", gravite: "attention" }, { titre: "Découvert en fin de mois", detail: "Le loyer tombe le 2, la paie le 28 : la trésorerie est tendue les derniers jours.", gravite: "critique" }], fuites: [], opportunites: [], allocation: [], dettes: [], strategie_dettes: { nom: "", logique: "", mensualite_cible: 0, duree_actuelle_mois: 0, duree_optimisee_mois: 0, interets_evites: 0, leviers: [] }, feuille_de_route: [], automatisations: [], plan_90_jours: [{ semaine: "S1", action: "Résilier Basic Fit (non utilisé depuis juin)", impact: "+30 € / mois", difficulte: "facile" }, { semaine: "S2", action: "Virement automatique de 100 € vers le livret le 29", impact: "Épargne de sécurité à 3 mois en 14 mois", difficulte: "facile" }, { semaine: "S4", action: "Demander à la banque de décaler le prélèvement du crédit au 5", impact: "Fin des agios", difficulte: "moyen" }], hypotheses: ["Le loyer inclut les charges"], questions: ["Ton crédit conso a-t-il des frais de remboursement anticipé ?"], mot_du_daf: "Tu n'es pas en danger, tu es sans filet. Trois mois de discipline et tu respires." };
  if (mod === "audit") { base.titre = "Audit de ton argent"; base.score = { global: 52, budget: 58, epargne: 30, depenses: 55, dettes: 60, securite: 40 }; base.fuites = [{ poste: "PRLV BASIC FIT", categorie: "sport", cout_mensuel: 29.99, cout_annuel: 360, impact: "nul", action: "Résilie en ligne, non utilisé depuis juin." }]; base.opportunites = [{ titre: "Prime d'activité", gain_estime: "≈ 60 € / mois", effort: "faible", detail: "À ton niveau de revenu, fais la simulation sur caf.fr." }]; }
  if (mod === "fuites") { base.titre = "Fuites d'argent"; base.fuites = [{ poste: "PRLV BASIC FIT", categorie: "sport", cout_mensuel: 29.99, cout_annuel: 360, impact: "nul", action: "Résilie en ligne." }, { poste: "Agios et frais bancaires", categorie: "banque", cout_mensuel: 18, cout_annuel: 216, impact: "nul", action: "Décale le prélèvement du crédit après la paie." }, { poste: "Livraisons repas", categorie: "sorties", cout_mensuel: 85, cout_annuel: 1020, impact: "a_cadrer", action: "Garde une livraison par semaine." }]; }
  if (mod === "treso") { base.titre = "Optimisation du cash-flow"; base.allocation = [{ poste: "Logement et fixes", pourcentage: 45, montant_mensuel: 980, regle: "Prélèvements regroupés entre le 1er et le 5" }, { poste: "Courses et quotidien", pourcentage: 20, montant_mensuel: 436, regle: "Enveloppe hebdo de 100 €" }, { poste: "Plaisirs et sorties", pourcentage: 10, montant_mensuel: 218, regle: "Carte dédiée, rechargée le 1er" }, { poste: "Crédit", pourcentage: 10, montant_mensuel: 212, regle: "Prélevé le 5" }, { poste: "Épargne de sécurité", pourcentage: 10, montant_mensuel: 218, regle: "Virement auto le 29" }, { poste: "Imprévus", pourcentage: 5, montant_mensuel: 109, regle: "Sous-compte imprévus" }]; base.automatisations = [{ quoi: "Virement épargne", comment: "100 € le lendemain de la paie", frequence: "mensuel" }]; }
  if (mod === "dettes") { base.titre = "Destructeur de dettes"; base.dettes = [{ nom: "Crédit conso Sofinco", capital_restant: 4200, taux: 6.9, mensualite: 212, priorite: 1, action: "Verse 60 € de plus par mois une fois l'imprévu couvert." }]; base.strategie_dettes = { nom: "Accélération douce", logique: "Une seule dette : on garde 500 € d'imprévus, puis on ajoute 60 € par mois.", mensualite_cible: 272, duree_actuelle_mois: 22, duree_optimisee_mois: 17, interets_evites: 110, leviers: [{ titre: "Remboursement anticipé partiel", detail: "Vérifie l'absence de frais dans ton contrat." }] }; }
  if (mod === "suivi") { base.titre = "Bilan du mois"; base.score = { global: 61, budget: 64, epargne: 45, depenses: 60, dettes: 62, securite: 55 }; base.progres = [{ indicateur: "Reste chaque mois", avant: "170 €", apres: "260 €", tendance: "mieux", commentaire: "La salle résiliée et les livraisons divisées par deux se voient." }, { indicateur: "Épargne de sécurité", avant: "0,7 mois", apres: "0,9 mois", tendance: "mieux", commentaire: "Le virement automatique a démarré." }, { indicateur: "Découvert", avant: "−120 €", apres: "−40 €", tendance: "stable", commentaire: "Encore un passage dans le rouge le 27." }]; base.actions_validees = [{ action: "Résilier Basic Fit", effet: "+30 € par mois, visible dès ce mois-ci." }]; base.actions_en_attente = [{ action: "Décaler le prélèvement du crédit au 5", conseil: "Un simple message depuis l'appli de ta banque suffit, cinq minutes." }]; base.defi_du_mois = { titre: "Zéro découvert en octobre", detail: "Garde 60 € de côté le 20 pour passer le 27 sans agios.", gain_estime: "18 € d'agios évités" }; base.plan_90_jours = [{ semaine: "S1", action: "Décaler le prélèvement du crédit au 5", impact: "Fin des agios", difficulte: "facile" }, { semaine: "S2", action: "Passer le virement épargne à 120 €", impact: "Sécurité à 3 mois en 12 mois", difficulte: "facile" }]; base.mot_du_daf = "Tu as tenu le cap : un mois de plus comme ça et le découvert n'est qu'un souvenir."; }
  if (mod === "plan") { base.titre = "Plan de richesse"; base.opportunites = [{ titre: "Négociation salariale", gain_estime: "+80 à 120 € / mois", effort: "moyen", detail: "Entretien annuel en novembre." }]; base.feuille_de_route = [{ horizon: "0-3 mois", objectif: "Arrêter le découvert", actions: ["Décaler le crédit", "Résilier la salle"], indicateur: "Solde > 0 le 27" }, { horizon: "3-6 mois", objectif: "1 000 € de sécurité", actions: ["100 € / mois automatiques"], indicateur: "Livret à 1 000 €" }]; }
  return base;
}
function respond(body) {
  if (body.action === "login") return String(body.email || "").toLowerCase() === "sam@exemple.fr" && body.password === "provisoire-1234" ? { ok: true, code: "PXP-TEST", label: "Sam", expires: "2026-12-31", product: "perso", email: "sam@exemple.fr", mustChange: true } : { ok: false, error: "E-mail ou mot de passe incorrect." };
  if (body.action === "password") return body.current === "provisoire-1234" && String(body.password || "").length >= 8 ? { ok: true, email: body.email } : { ok: false, error: "Mot de passe actuel incorrect." };
  if (body.action === "verify") return String(body.code || "").toUpperCase() === "PXP-TEST" ? { ok: true, label: "TEST", expires: "2026-12-31", product: "perso", quota: { used: 1, limit: 5 } } : { ok: false, error: "Code inconnu. Vérifie les tirets et les majuscules." };
  if (body.action === "lecture") return { ok: true, action: "lecture", result: ETAT, quota: { used: 2, limit: 5 } };
  if (body.action === "analyse") return { ok: true, action: "analyse", module: body.module, result: rapport(body.module), quota: { used: 2, limit: 5 } };
  return { ok: false, error: "Action inconnue." };
}
module.exports = { ETAT: ETAT, rapport: rapport, respond: respond };
